#ifndef _PACKET_H_
#define _PACKET_H_

#define ETHER_OFF_DST 0
#define ETHER_OFF_SRC 6
#define ETHER_OFF_TYPE 12
#define ETHER_OFF_ARP 14
#define ETHER_TYPE_ARP 0x0806
#define ETHER_TYPE_IPV4 0x0800

#define ARP_OFF_HARDWARE ETHER_OFF_ARP + 0
#define ARP_OFF_PROTOCOL ETHER_OFF_ARP + 2
#define ARP_OFF_HARDWARE_SIZE ETHER_OFF_ARP + 4
#define ARP_OFF_PROTOCOL_SIZE ETHER_OFF_ARP + 5
#define ARP_OFF_OPCODE ETHER_OFF_ARP + 6
#define ARP_OFF_SENDER_MAC ETHER_OFF_ARP + 8
#define ARP_OFF_SENDER_IP ETHER_OFF_ARP + 14
#define ARP_OFF_TARGET_MAC ETHER_OFF_ARP + 18
#define ARP_OFF_TARGET_IP ETHER_OFF_ARP + 24

#endif // _PACKET_H_
