#ifndef _PACKET_H_
#define _PACKET_H_

#define ETHER_OFF_DST 0
#define ETHER_OFF_SRC 6
#define ETHER_OFF_TYPE 12
#define ETHER_OFF_ARP 14
#define ETHER_OFF_IPV4 14
#define ETHER_TYPE_ARP 0x0806
#define ETHER_TYPE_IPV4 0x0800
#define ETHER_HEADER_LEN 14

#define IPV4_PROTOCOL_ICMP 1
#define IPV4_HEADER_LEN 20

#define IPV4_OFF_VER_LEN ETHER_OFF_IPV4 + 0
#define IPV4_OFF_DSF ETHER_OFF_IPV4 + 1
#define IPV4_OFF_TOTAL_LEN ETHER_OFF_IPV4 + 2
#define IPV4_OFF_ID ETHER_OFF_IPV4 + 4
#define IPV4_OFF_FLAGS ETHER_OFF_IPV4 + 6
#define IPV4_OFF_TTL ETHER_OFF_IPV4 + 8
#define IPV4_OFF_PROTOCOL ETHER_OFF_IPV4 + 9
#define IPV4_OFF_CHECKSUM ETHER_OFF_IPV4 + 10
#define IPV4_OFF_SRC ETHER_OFF_IPV4 + 12
#define IPV4_OFF_DST ETHER_OFF_IPV4 + 16
#define IPV4_OFF_END ETHER_OFF_IPV4 + 20

#define ARP_OFF_HARDWARE ETHER_OFF_ARP + 0
#define ARP_OFF_PROTOCOL ETHER_OFF_ARP + 2
#define ARP_OFF_HARDWARE_SIZE ETHER_OFF_ARP + 4
#define ARP_OFF_PROTOCOL_SIZE ETHER_OFF_ARP + 5
#define ARP_OFF_OPCODE ETHER_OFF_ARP + 6
#define ARP_OFF_SENDER_MAC ETHER_OFF_ARP + 8
#define ARP_OFF_SENDER_IP ETHER_OFF_ARP + 14
#define ARP_OFF_TARGET_MAC ETHER_OFF_ARP + 18
#define ARP_OFF_TARGET_IP ETHER_OFF_ARP + 24

struct ether_frame {
    uint8_t dst[6];
    uint8_t src[6];
    uint16_t type;
};

#endif // _PACKET_H_
